# certaines images ont plusieurs type d'images, ex : phpmyadmin/mysql
# ici on reste sur phpmyadmin plus large au dépent de la taille, permet de changer de bdd sans avoir à changer dockerfile
FROM phpmyadmin/phpmyadmin:latest

# Exposer le port 80
EXPOSE 80
